name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Targets
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
#           - os: macos-latest
#             platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          # A directory to store and save the cache
          path: ./cache
          # An explicit key for restoring and saving the cache
          key: abc123abc
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Install X11 Development Libraries
        run: |
          if [[ "${{ matrix.platform }}" == "linux" || "${{ matrix.platform }}" == "ubuntu" ]]; then
            sudo apt-get update
            sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxrandr-dev libxrender-dev libxtst-dev libasound2-dev libpulse-dev libjack-dev libnss3-dev libxcursor-dev libxss-dev libgtk-3-dev libwebkit2gtk-4.0-dev
          elif [[ "${{ matrix.platform }}" == "mac" ]]; then
            brew update
            brew install libx11 libxrandr libxinerama libxcursor libxcomposite libxdamage libxext libxfixes libxi libxrandr libxrender libxtst libsoundio libpulse jack nss libxcursor libxss gtk+3 webkit2gtk
          fi
          
          

      - name: Build Target
        run: |
          cmake -S . -B build/${{ matrix.platform }}
          cmake --build build/${{ matrix.platform }} --config Release
          
      # Upload Artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: ./build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/${{ matrix.platform }}/ProiEqualizer.so
            build/${{ matrix.platform }}/ProiEqualizer.vst3
            build/${{ matrix.platform }}/ProiEqualizer.exe
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
